# Generated by Django 2.1.7 on 2019-03-19 03:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microblog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='refill',
            name='number',
        ),
        migrations.AddField(
            model_name='refill',
            name='refill_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='refill',
            name='nickname',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='refill',
            name='pharmacy',
            field=models.CharField(blank=True, max_length=240, null=True),
        ),
        migrations.AlterField(
            model_name='refill',
            name='prescription',
            field=models.CharField(max_length=60),
        ),
    ]
