# Generated by Django 2.1.7 on 2019-03-15 23:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('microblog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RefillEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.CharField(max_length=160)),
                ('location', models.CharField(max_length=160)),
                ('description', models.TextField()),
                ('startdatetime', models.DateTimeField()),
                ('enddatetime', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='tweet',
            name='liked',
            field=models.ManyToManyField(related_name='liked_tweets', to=settings.AUTH_USER_MODEL),
        ),
    ]
