# Generated by Django 2.1.7 on 2019-03-19 23:30

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microblog', '0002_auto_20190319_0331'),
    ]

    operations = [
        migrations.AddField(
            model_name='refill',
            name='all_day',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='refill',
            name='often',
            field=models.IntegerField(blank=True, default=1, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)]),
        ),
        migrations.AddField(
            model_name='refill',
            name='refill_time',
            field=models.TimeField(blank=True, default=datetime.time(12, 0), null=True),
        ),
        migrations.AddField(
            model_name='refill',
            name='repeats',
            field=models.CharField(blank=True, choices=[('weeks', 'weeks'), ('months', 'months')], max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='refill',
            name='nickname',
            field=models.CharField(blank=True, help_text='Optional: Name that will display on calendar event instead of Medicine Name', max_length=60, null=True, verbose_name='Medicine Nickname'),
        ),
        migrations.AlterField(
            model_name='refill',
            name='pharmacy',
            field=models.CharField(blank=True, help_text='Name and Location', max_length=240, null=True, verbose_name='Pharmacy for Refill'),
        ),
        migrations.AlterField(
            model_name='refill',
            name='prescription',
            field=models.CharField(help_text='Medicine Name', max_length=60),
        ),
        migrations.AlterField(
            model_name='refill',
            name='refill_date',
            field=models.DateField(default=datetime.date.today, help_text='Next date to refill med'),
        ),
    ]
