# Generated by Django 2.1.7 on 2019-03-20 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microblog', '0006_auto_20190320_0121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refill',
            name='timezone',
            field=models.CharField(choices=[('America/Los_Angeles', 'Pacific'), ('America/Denver', 'Mountain'), ('America/Chicago', 'Central'), ('America/New_York', 'Eastern')], default='Pacific', help_text='Timezone of first refill date', max_length=20),
        ),
    ]
