# Generated by Django 2.1.7 on 2019-03-23 19:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microblog', '0008_remove_refill_timezone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='refillevent',
            name='user',
        ),
        migrations.AlterField(
            model_name='refill',
            name='often',
            field=models.IntegerField(blank=True, default=1, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)], verbose_name='Repeates Every'),
        ),
        migrations.AlterField(
            model_name='refill',
            name='repeats',
            field=models.CharField(blank=True, choices=[('WEEKLY', 'weeks'), ('MONTHLY', 'months')], max_length=9, null=True, verbose_name=''),
        ),
        migrations.DeleteModel(
            name='RefillEvent',
        ),
    ]
